name = "GPP_Bogo_v_Boltz"
uuid = "8d9ff2b0-75c1-4dff-966b-4cbe4ff0675a"
version = "0.1.0-DEV"
authors = ["not-physicist"]

[deps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
CubicSplines = "9c784101-8907-5a6d-9be6-98f00873c89b"
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearInterpolations = "b20c7882-2490-4592-a606-fbbfe9e745e8"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MultiQuad = "8fca5bbe-a785-4bb7-9793-c0c8ddca5d4b"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BSplineKit = "0.19.1"
CubicSplines = "0.2.1"
CurveFit = "0.6.1"
NPZ = "0.4"
OrdinaryDiffEq = "6"
Peaks = "0.5.3"
ProgressBars = "1.5.1"
QuadGK = "2.11.2"
Serialization = "1.11.0"
StaticArrays = "1"
Statistics = "1.11.1"
julia = ">=1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
